// INCLUDE FILE generated by "Pelles C for Windows, version 1.00".

#define DIALOG_CLASS	"Update_Tool_Class"

#define DLG_MAIN  1001
#define IDR_ICO_MAIN  8001
#define ID_EDIT  4001
#define ID_CB_SERIAL  4002
#define ID_BT_CONNECT  4003
#define ID_CB_SPEED  4005
#define ID_BT_SPEED  4006
#define ID_BT_CLR_SCR  4004
#define ID_BT_SAVE  4007
#define ID_CB_uC  4008
#define ID_CHK_ERASE  4009
#define ID_PROGRESS  4010
#define ID_LBL_PROGRESS  4011
#define ID_BT_SELECT_IMAGE  4013
#define ID_BT_UPDATE  4014
#define ID_BT_RESET  4015
#define ID_CHK_HEX  4016

#define ID_ED_IMG_FILE  4012
#define ID_ED_CMD  4017
#define ID_BT_SEND_CMD  4018
#define ID_MENU  2001
#define ID_STATUS_BAR  4019
#define ID_MENU_DOWNLOAD_SPEED  6001
#define ID_MENU_ABOUT  6002
#define ID_DL_SPEED_115K  6003
#define ID_DL_SPEED_460K  6004
#define ID_DL_SPEED_921K  6005
#define ID_DL_SPEED_1M  6006
#define ID_DL_SPEED_2M  6007
#define ID_IMG_W800  8002
#define DLG_ABOUT  1002
#define ID_SPLITBT_TEST  4020
#define ID_LBL_PROGRESS_DESC  4021
#define ID_MENU_QRY_WIFI  6008
#define ID_MENU_QRY_BT  6009
#define ID_MENU_QRY_QFLASH  6010
#define ID_MENU_QRY_ROM  6011
#define ID_MENU_INPUT_NORMAL  6012
#define ID_MENU_INPUT_CR  6013
#define ID_MENU_INPUT_NL  6014
#define ID_MENU_INPUT_CRNL  6015
#define ID_MENU_INPUT_HEX  6016
#define ID_MENU_ROM_MONITOR  6017
